### ISSUE TITLE
change the artnet universe

### ISSUE THREAD

**Issue by JoFo112** [robertoostenveld/arduino#14]
When I try to change the artnet universe the D1 mini restarts and the universe has not chanchst.

**Comment by robertoostenveld** [comment]
this should happen around here https://github.com/robertoostenveld/arduino/blob/080945494c4f9903c10332dbad0eda696e98cef7/esp8266_artnet_dmx512/setup_ota.cpp#L228 and here https://github.com/robertoostenveld/arduino/blob/080945494c4f9903c10332dbad0eda696e98cef7/esp8266_artnet_dmx512/setup_ota.cpp#L73. You may want to add some debug information with Serial.println and connect over USB to see what is going on. Please send a pull request if you can improve the code.
