### ISSUE TITLE
artnet_neopixel SPIFFS Upload issue?

### ISSUE THREAD

**Issue by sisensee** [robertoostenveld/arduino#16]
Sketch compiles in latest IDE, no obvious errors. SPIFFS Data uploader says it completes upload. unable to browse /index or any other files outside of wifi setup pages.

**Comment by robertoostenveld** [comment]
is the connection to the http server successful, and is it a spiffs issue or a http issue? Please add in the `setup()` section somewhere between line 130 and 235 this piece

```
  server.on("/version", HTTP_GET, []() {
    Serial.println("version");
    server.send(200, "text/plain", version);
  });
```

Then you can GET `http://arttnet.local/version` and you should see the firmware version. Or try with `http://arttnet.local/dir`, which should show you the list of files on the SPIFFS.

What do you see if you listen on the serial interface?

**Comment by sisensee** [comment]
I do not think the web server is running, it works for the Wifi setup (which made me think web server was working and not even look down that path). 
I previously was getting file not founds in the serial monitor now I just get nothing. iPhone gives "Safari could not open the page because the server stopped responding"

Serial Monitor
"
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 1
*WM: 
*WM: Configuring access point... 
*WM: ARTNET
*WM: Custom AP IP/GW/Subnet
*WM: AP IP address: 
*WM: 192.168.1.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Scan done
*WM: DUP AP: SMS-EMP
*WM: DUP AP: SMS-EMP
*WM: DUP AP: SMS-EMP
*WM: DUP AP: SMS-EMP
*WM: DUP AP: SMS-VENDOR
*WM: DUP AP: SMS-VENDOR
*WM: DUP AP: SMS-VENDOR
*WM: SMS-EMP
*WM: -55
*WM: SMS-VENDOR
*WM: -56
*WM: SMARTWIRE
*WM: -61
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Handle root
*WM: WiFi save
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Connection result: 
*WM: 3
connected
setup done
*WM: freeing allocated params!
{$�lܞ⸮⸮c⸮o⸮$⸮c|⸮⸮⸮p⸮⸮|c⸮p⸮⸮no⸮�$Nn⸮⸮⸮"p⸮#d rlp⸮N⸮⸮l⸮⸮cN⸮⸮nl⸮⸮b⸮|⸮N⸮l⸮⸮�d ⸮oNl`Ns⸮ےNB⸮lr⸮⸮nb⸮d⸮⸮ll⸮⸮{$⸮⸮o⸮setup starting
loadConfig
Failed to open config file
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 10.101.235.159
connected
setup done
*WM: freeing allocated params!
"

IDE Output for uploading sketch and SPIFFS 

`
Sketch uses 402008 bytes (38%) of program storage space. Maximum is 1044464 bytes.
Global variables use 35156 bytes (42%) of dynamic memory, leaving 46764 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.8-dev
2.8-dev
esptool.py v2.8-dev
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: ec:fa:bc:05:86:42
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 406160 bytes to 281371...

Writing at 0x00000000... (5 %)
Writing at 0x00004000... (11 %)
Writing at 0x00008000... (16 %)
Writing at 0x0000c000... (22 %)
Writing at 0x00010000... (27 %)
Writing at 0x00014000... (33 %)
Writing at 0x00018000... (38 %)
Writing at 0x0001c000... (44 %)
Writing at 0x00020000... (50 %)
Writing at 0x00024000... (55 %)
Writing at 0x00028000... (61 %)
Writing at 0x0002c000... (66 %)
Writing at 0x00030000... (72 %)
Writing at 0x00034000... (77 %)
Writing at 0x00038000... (83 %)
Writing at 0x0003c000... (88 %)
Writing at 0x00040000... (94 %)
Writing at 0x00044000... (100 %)
Wrote 406160 bytes (281371 compressed) at 0x00000000 in 24.8 seconds (effective 130.8 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
[SPIFFS] data    : /Users/seanisensee/Downloads/arduino-master 2/esp8266_artnet_neopixel/data
[SPIFFS] size    : 3052
[SPIFFS] page    : 256
[SPIFFS] block   : 8192
/favicon.ico
/update.html
/index.html
/reload_failure.html
/hello.html
/monitor.js
/cat.jpg
/style.css
/jquery-3.1.1.min.js
/reload_success.html
/settings.html
/monitor.html
/settings.js
[SPIFFS] upload  : /var/folders/c6/q93qkd1x4lb9n1l3jfxy0bnh0000gn/T/arduino_build_232733/esp8266_artnet_neopixel.spiffs.bin
[SPIFFS] address  : 0x100000
[SPIFFS] reset    : nodemcu
[SPIFFS] port     : /dev/cu.SLAB_USBtoUART
[SPIFFS] speed    : 115200
[SPIFFS] python   : /Users/seanisensee/Library/Arduino15/packages/esp8266/tools/python/3.7.2-post1/python
[SPIFFS] uploader : /Users/seanisensee/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/upload.py

esptool.py v2.8-dev
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: ec:fa:bc:05:86:42
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 3125248 bytes to 53323...

Writing at 0x00100000... (25 %)
Writing at 0x00104000... (50 %)
Writing at 0x00108000... (75 %)
Writing at 0x0010c000... (100 %)
Wrote 3125248 bytes (53323 compressed) at 0x00100000 in 4.7 seconds (effective 5283.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
`

**Comment by robertoostenveld** [comment]
what does http://arttnet.local/version return? That link should confirm that the http server is running, and does not use anything from SPIFS.

Can you ping it? Is there any network connection possible after going through the wiki manager configuration?

**Comment by sisensee** [comment]
I can ping it, get no response from /version at all and when I do a port scan on the IP I get no open ports at all. So the webserver is not functioning.

**Comment by robertoostenveld** [comment]
Then it is not a SPIFS problem, but a web server problem. Probably you are working with libraries that have all been updated to more recent versions compared to the last time I compiled and flashed the firmware. I propose you try first with a simpler sketch, e.g. with a hard-wired wifi setup (skipping WiFiManager) and e.g. one of https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples. If that works, you can increase the complexity of the sketch step by step.

**Comment by sisensee** [comment]
if I reset and join Artnet wifi manager is running on port 80 (as expected)
But once the device is on network web server is not opening a port.
<img width="907" alt="Screen Shot 2019-09-24 at 7 57 11 AM" src="https://user-images.githubusercontent.com/1280696/65523333-fc449f00-dea0-11e9-92c0-b66911e57dea.png">

**Comment by sisensee** [comment]
You sir are 100% correct. Even the basic web server examples are not functioning, can I ask what version (from board manager) you are using for the ESP8266? Currently I'm on 2.5.2

**Comment by robertoostenveld** [comment]
how can I quickly determine the ESP8266 version?

**Comment by sisensee** [comment]
Arduino IDE > Tools > Board > Board Manager > Search "esp8266"
PS Thanks for the responses!

**Comment by sisensee** [comment]
Ive tried this with a few NodeMCU's and a Wemos (d1 mini lite) and still have the same results so I don't think its chip,

**Comment by sisensee** [comment]
Also running Arduino IDE 1.8.10 (thought id mentioned that)

**Comment by robertoostenveld** [comment]
I have not done anything with Arduino for some time, but did get a new MacBook recently. I think all software was properly transferred from the old one to the one I am currently working on:

 I have Arduino 1.8.7, and under board manager I see that I have esp8266 version 2.4.2. So both are older than the ones you are working with. 

Since I don't have reasons to believe that it is a problem specific to my sketch, let me close this issue.

**Comment by sisensee** [comment]
Thank you for the assistance and pointing me in the right direction!
