### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Barabba11** [robertoostenveld/arduino#17]
Hi, after tried everything possible with Matthew Tong and Robert Oostenveld I tried with yours, as the problem I'm probably facing with their releases is the jitter problem, the signal outputs but fixtures don't catch it. 
I tried yours, and after some work trying to find around all the libraries needed I found out that it connects to the wifi router, but it doesn't answer the broadcast, i've tested it with DMX-Workshop which can't discover my Wemos D1, i can ping it but no dmx support.
I would recomend you to realize a .bin file to upload it easy, this will save us for any stupid mistake we may do or have compile problems. Thank you a lot

**Comment by robertoostenveld** [comment]
I am not planning to release precompiled firmwares. I would welcome it if someone (e.g. you) were to release binary firmware versions for the different ESP boards, and provide support for them.

**Comment by Barabba11** [comment]
Thanks for reply/support, I've tried different releases, there are many around, anyway I've found one that works and it's also stable, for who is interested I paste link here: https://github.com/bombcheck/ESP8266_ArtNet-LED-DMX-Node.

**Comment by robertoostenveld** [comment]
Thanks, I will add a link to it in the documentation.
