### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [robertoostenveld/arduino#18]
Hello!

I found link to this project from https://robertoostenveld.nl/art-net-to-dmx512-with-esp8266/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by robertoostenveld** [comment]
Hi @vazhnov,

The code that I wrote and/or collected in this repository is mostly a mash-up of code snippets and information that I found at various places on the internet. There are pieces where I am not even sure if I could be considered the original author. For the pieces of code here in which I invested more substantial (creative) efforts, I am happy to share back to the community without restrictions. So please consider it to be in the public domain, i.e. you can do with it what you want. See https://fairuse.stanford.edu/overview/public-domain/welcome/.

Note that this does not apply to the Arduino core, applications, or any libraries that might be used by the code in this repository; those are covered by their respective licenses. 

best regards,
Robert

**Comment by vazhnov** [comment]
@robertoostenveld , could you please add a note into `README.md`, for example create chapter "License" and copy your text above?

Also, please, take a look at [cc0](https://creativecommons.org/share-your-work/public-domain/cc0/), maybe it is a better description of what you want.

**Comment by robertoostenveld** [comment]
With cc0 I would claims rights as being the creator, which is not appropriate in some cases. Hence I think that  https://en.wikipedia.org/wiki/Public_domain is more suited to describe the situation. 

I added something to the readme.
