### ISSUE TITLE
esp8266_artnet_dmx512: Device loses StandAlone configuration

### ISSUE THREAD

**Issue by Black-Zero** [robertoostenveld/arduino#19]
Hello,

I am having an issue with the esp8266 artnet dmx512 project. Perhaps you can help me please.
I have set up the device though it connects to an access point (router). That works very well. I also configured it that it will set up an custom StandAlone Access Point (custom host name and password), if it looses the connection to the router.

Unfortunately after some time it will loose the information about the StandAlone Access Point and it will display me an SSID with "ESP-xxxxxx" with no password protection. But also a connection via router is possible. This is a big security issue for me, thus I don't want that other people can mess with the esp...

Is there any idea how I can fix this?

Thank you very much!

Black-Zero

**Comment by robertoostenveld** [comment]
This seems a generic wifi issue and not specific to artnet or dmx512. 

I suspect this has to do with poor wifi reception. Note that the onboard antenna of the esp8266 is not so great. I have this issue as well with some of my [tasmota](https://github.com/tasmota) switches that are relatively far away from my access point and/or behind metal objects that interfere with the radio signal. However, with the tasmota firmware the esp8266 firmware only opens up as a (configurable) "ESP-xxxxxx" access point for a few minutes, then it switches off again.  

You may want to check with https://github.com/tzapu/WiFiManager whether there is an option to limit the duration of the over-the-air-configuration. And/or place it closer to your normal wifi access point.

Good luck,
Robert

**Comment by Black-Zero** [comment]
Hello,

I am using an external Antenna and wifi connection to the router is quite good.
The Node is working fine while connected to the router and still displaying the "ESP-xxxxxx" Network.

My issue is not, that he is still displaying his own standalone access point. It's rather, that he loses his standalone wifi settings. At the first time he opens up a Wifi Network with e.g. name: "Test", IP 192.168.1.1 and a password. It doesn't take long after I connected it to my wlan router, that he forgets his own standalone settings and will offer me a Network with name "ESP-xxxxxx" and IP 192.168.1.1 with no password settings.

I don't think that this is about poor wifi reception. Then it would display me my setted up Network "Test".

Any ideas, or still WifiManager?

Thank you very much!

Greetings,
Black-Zero
