### ISSUE TITLE
missing String.h library

### ISSUE THREAD

**Issue by smadds** [robertoostenveld/arduino#4]
Arduino IDE (1.8.5) compilation is failing:

`In file included from /home/simon/robertoostenveld.arduino/esp8266_artnet_dmx512/esp8266_artnet_dmx512.ino:17:0:
sketch/setup_ota.h:6:20: fatal error: String.h: No such file or directory
 #include <String.h>` 

I'm compiling to "WeMos D1 mini Pro" and my board definitions are up to date.

Any idea where I can locate this library?

**Comment by robertoostenveld** [comment]
sorry, String.h was not needed. I also don't have it on my computer (macOS with Arduino 1.8.7), but the compiler did not complain about it.
