### ISSUE TITLE
Which version of IDE?

### ISSUE THREAD

**Issue by sisensee** [robertoostenveld/arduino#6]
Trying to compile this again (new computer), its been a while since ive flashed the code to anything, getting random errors and was wondering what version of IDE was used to compile with?

**Comment by sisensee** [comment]
Nevermind it was the version of arduinojson that was complicating things. I had to revert to version 5.13.1 just in case someone comes around and finds this. Ide 1.8.4

**Comment by robertoostenveld** [comment]
Glad to hear that you found the solution.
