### ISSUE TITLE
ESP8266_artnet_dmx512 schematics or more thorough assembly directions?

### ISSUE THREAD

**Issue by rabbiccu** [robertoostenveld/arduino#8]
Is there a schematic for wiring? Some of the directions are vague and refer only to GND but not what GND, etc.

Thanks! Have components ordered, and now I wait!

**Comment by robertoostenveld** [comment]
On https://robertoostenveld.nl/art-net-to-dmx512-with-esp8266/ you can see some photo's.  I never made any schematics. If you do, please share them here. All GNDs are connected to each other.
